version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: quora-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: quora_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 10

  redis:
    image: redis:7.2-alpine
    container_name: quora-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes --requirepass redis123
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
  redis_data: